XS - FEATURE: Improve the usability of the admin DriverAvailabiltyIndexPage
ucsb-cs156-s24/proj-gauchoride-s24-5pm-8 pull request #23
Opened 2024-05-20 06:00 UTC by xinyao-song

### Description
Removed the `ButtonColumn` for Review in Admin's view but kept the `buttonColumnsAdmin` structure incase further implementation is necessary.  
Added a link for `Driver Id` similar to `ShiftsTable.js`

### Acceptance Criteria

- [ ] Admin can click on the Driver Id and it will take them to the same information page that you get from the Shifts page.
- [ ] Review button is removed

Dokku: https://gauchoride-xinyao-dev.dokku-16.cs.ucsb.edu

2024-05-22 00:01 UTC, TheRealAndrxw approved these changes
LGTM

2024-05-23 05:34 UTC, pconrad requested changes
Could you deploy this on a dokku dev instance and link to that instance on the PR description?

2024-05-23 08:39 UTC, xinyao-song commented
Added Dokku deployment link in the PR description

2024-05-26 00:16 UTC, pconrad commented
I could use some help to know what to test here.  A "before" screenshot would be helpful, plus an improved description along these lines:

https://ucsb-cs156.github.io/topics/pull_requests/#pr-descriptions

2024-05-28 18:09 UTC, pconrad approved these changes

2024-05-28 18:09 UTC, pconrad approved these changes
LGTM

2024-05-28 18:10 UTC, merged