EPIC: Improve usability of the DriverAvailabilities Create Page
ucsb-cs156-s24/proj-gauchoride-s24-5pm-8 pull request #24
Opened 2024-05-21 04:40 UTC by xinyao-song

### Description:

**Backend:**
- Modify DriverAvailabilityController.java `POST` so that when creating a new DriverAvailability we automatically use the creator's id and no longer take in id as an input.
- Modify DriverAvailabilityController.java `PUT` so that when editing DriverAvailability we make sure that the DriverAvailability we intend to edit is really owned by the current user, and we no longer want to set the driver id to the incoming.
- Add the proper validations to `GET` single and `DELETE` so that a user can only delete or get their own availabilities and not anyone else's

**Frontend:**
- Improved readability of the availability form
- Removed driverId
- Added a selection bar for available dates and format indicator for start and end time
- Modified `DriverAvailabilityForm.test.js` so driverId is not included. 
- Added  `act(() => {});` in `DriverAvailabilityForm.test.js` to fix the warning 
```
Warning: An update to DriverAvailabilityForm inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
```
- Modified `DriverAvailabilityEditPage.test.js` so driverId is not included. 

### Acceptance Criteria:

- [ ] The form labels are improved
- [ ] The bad input and missing input error messages are added and improved
- [ ] Example inputs on each form field

### BLOCKER:
After driverId is removed, the following failed test exist
```
Summary of all failing tests
 FAIL  src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
  ● DriverAvailabilityCreatePage tests › on submit, makes request to backend, and redirects to /availability

    TestingLibraryElementError: Unable to find a label with the text of: driverId
```
However, when driverId Is removed from` DriverAvailabilityCreatePage.js` and the corresponding `DriverAvailabilityCreatePage.test.js` the following issue shows:
```
DriverAvailabilityCreatePage tests › on submit, makes request to backend, and redirects to /availability

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0
```
I logged the change, it seems that `axiosMock.history.post.length `were never 1. 
```
 console.log
      Axios Mock History: []

      at src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js:105:21

    console.log
      Axios Mock History: []

      at src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js:105:21

    console.log
      Axios Mock History: []

      at src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js:105:21
```

### Preview:
<img width="1440" alt="Screenshot 2024-05-20 at 9 20 55 PM" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/assets/42160992/153f686f-2789-45c6-8903-a535550d052e">
<img width="1440" alt="Screenshot 2024-05-20 at 9 21 08 PM" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/assets/42160992/035b9e92-804a-4488-bfc6-369a5252b20e">
<img width="1440" alt="Screenshot 2024-05-20 at 9 21 18 PM" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/assets/42160992/5b64a98f-9947-4e50-855d-8391a5adf9f9">
<img width="1440" alt="Screenshot 2024-05-20 at 9 21 36 PM" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/assets/42160992/70b66f54-ce74-496a-8648-1b9f586028bd">
<img width="1440" alt="Screenshot 2024-05-20 at 9 22 03 PM" src="https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/assets/42160992/3f2071a1-7689-405f-abfc-ede73aba2d00">

2024-05-22 04:27 UTC, spark686 approved these changes, later dismissed
LGTM

2024-05-22 17:30 UTC, Hannahshakouri01 approved these changes, later dismissed
nice work, LGTM!

2024-05-23 05:39 UTC, pconrad reviewed
This is a lot of work!  Accordingly I think I want to test it on a dokku deployment before I'd merge it.

2024-05-23 08:37 UTC, xinyao-song commented
Added Dokku deployment link along with testing instructions

2024-05-26 00:25 UTC, pconrad requested changes
I think the PR description could be better.. I made some specific suggestions in the team slack channel.

Also: I wonder why description is required?  Seems like that should be optional.

Otherwise, the code looks really good.

2024-05-26 00:25 UTC, pconrad commented on frontend/src/main/components/Driver/DriverAvailabilityForm.js
> +          {...register("notes", {
Consider making this optional.  I don't think making this required is going to be a good user experience.

2024-05-28 18:14 UTC, pconrad approved these changes, later dismissed
LGTM

2024-05-28 18:15 UTC, merged