sp - FEATURE: Admin table should not move entries after a toggle button is pressed
ucsb-cs156-s24/proj-gauchoride-s24-5pm-8 pull request #38
Opened 2024-05-29 00:11 UTC by spark686

I sorted the users table based on id. It the ordering of the  not move after admin pressing driver toggle button. 

+  User table is sorted by some metric
+ When a property of a user is toggled, they should remain in the same position in the table (instead of moving to the bottom)

dokku deployment:
      https://final-spark686-sort.dokku-16.cs.ucsb.edu

2024-05-29 23:11 UTC, bradygin approved these changes, later dismissed
LGTM! Just linked your issue so that it will be closed when this is merged

2024-05-30 00:29 UTC, Hannahshakouri01 submitted a review, later dismissed
LGTM!

2024-06-03 22:30 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // const [sortedUsers, setSortedUsers] = useState(users);
Commented out code?  https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-03 22:30 UTC, pconrad requested changes
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-03 22:30 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // }, [users, sort]);
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-03 22:30 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
> +    // }
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-03 22:30 UTC, pconrad commented on frontend/src/main/components/Users/UsersTable.js
>      //const columnsToDisplay = showButtons ? buttonColumn : columns;
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-03 22:30 UTC, pconrad commented on frontend/src/tests/components/Users/UsersTable.test.js
> +// }));
https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html#why-should-commented-out-code-be-removed

2024-06-05 00:25 UTC, pconrad approved these changes
LGTM... will test on dokku before merging

2024-06-05 00:44 UTC, whuang602 approved these changes
LGTM

2024-06-05 00:45 UTC, merged